import Image from 'next/image'
import { categories } from '@/lib/furngen-data'
import { SectionHeading } from './section-heading'

export function Catalogue() {
  return (
    <section id="catalogue" className="border-b border-border">
      <div className="mx-auto w-full max-w-6xl px-6 py-16 lg:py-24">
        <SectionHeading
          eyebrow="Catalogue"
          title="Six categories, twenty-eight types"
          description="Each type has its own dimension envelope, so a nightstand never inherits a sofa's proportions. Room sets place a coordinated group in one click."
        />

        <div className="mt-12 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">
          {categories.map((category) => (
            <article key={category.name} className="flex flex-col gap-4 bg-card p-6">
              <div className="flex items-baseline justify-between gap-3">
                <h3 className="text-lg font-medium tracking-tight">{category.name}</h3>
                <span className="font-mono text-xs text-muted-foreground">
                  {category.count} types
                </span>
              </div>
              <ul className="flex flex-wrap gap-1.5">
                {category.types.map((type) => (
                  <li
                    key={type}
                    className="rounded-sm bg-secondary px-2 py-1 font-mono text-[11px] text-secondary-foreground"
                  >
                    {type}
                  </li>
                ))}
              </ul>
            </article>
          ))}
        </div>

        <div className="mt-12 grid gap-8 overflow-hidden rounded-lg border border-border bg-card lg:grid-cols-[1.4fr_1fr] lg:gap-0">
          <div className="relative min-h-64 lg:min-h-full">
            <Image
              src="/images/room-set.png"
              alt="Complete living room set generated by FurnGen: sofa, coffee table, side table, floor lamp, rug, ottoman, bookshelf and plant"
              width={1024}
              height={1024}
              className="h-full w-full object-cover"
            />
          </div>
          <div className="flex flex-col items-start justify-center gap-4 p-6 lg:p-10">
            <p className="font-mono text-xs tracking-tight text-primary">Room sets</p>
            <h3 className="text-2xl font-medium tracking-tight text-balance">
              A whole living room from one button
            </h3>
            <p className="leading-relaxed text-muted-foreground text-pretty">
              The living room set places nine coordinated items and the bedroom set places six. Every
              piece shares the seed and the style, so the palette and the leg profiles stay
              consistent across the group — then each item is a separate named group you can move,
              swap or delete on its own.
            </p>
          </div>
        </div>
      </div>
    </section>
  )
}
