import Image from 'next/image'
import { SectionHeading } from './section-heading'

/**
 * Four renders of the same category -- a sofa -- under four different styles,
 * to make the point that a style changes silhouette and not just colour.
 */
const shots = [
  {
    src: '/images/style-scandinavian.png',
    style: 'Scandinavian',
    spec: 'rounded arms · cone legs · linen',
    seed: '10294',
  },
  {
    src: '/images/style-luxury.png',
    style: 'Luxury',
    spec: 'rounded arms · cylinder legs · velvet',
    seed: '77310',
  },
  {
    src: '/images/style-brutalism.png',
    style: 'Brutalism',
    spec: 'square arms · no legs · cotton',
    seed: '20488',
  },
  {
    src: '/images/style-midcentury.png',
    style: 'Mid-century',
    spec: 'pillow arms · cone legs · bouclé',
    seed: '61905',
  },
]

export function Gallery() {
  return (
    <section className="border-b border-border">
      <div className="mx-auto w-full max-w-6xl px-6 py-16 lg:py-24">
        <SectionHeading
          eyebrow="Output"
          title="One category, four styles"
          description="Every image below is the same request — a three-seat sofa — with only the style changed. The armrest silhouette, leg profile, seat depth and palette all move together."
        />

        <ul className="mt-12 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2">
          {shots.map((shot) => (
            <li key={shot.style} className="flex flex-col bg-card">
              <Image
                src={shot.src}
                alt={`A sofa generated by FurnGen in the ${shot.style} style: ${shot.spec}`}
                width={1024}
                height={1024}
                className="h-auto w-full"
              />
              <div className="flex items-baseline justify-between gap-3 border-t border-border p-5">
                <div className="flex flex-col gap-1">
                  <h3 className="font-medium tracking-tight">{shot.style}</h3>
                  <p className="font-mono text-[11px] text-muted-foreground">{shot.spec}</p>
                </div>
                <span className="font-mono text-[11px] whitespace-nowrap text-muted-foreground">
                  seed {shot.seed}
                </span>
              </div>
            </li>
          ))}
        </ul>
      </div>
    </section>
  )
}
