import Image from 'next/image'
import { ArrowRight, BookOpen } from 'lucide-react'
import { REPO_URL } from '@/lib/furngen-data'

const stats = [
  { value: '28', label: 'furniture types' },
  { value: '8', label: 'design styles' },
  { value: '5', label: 'upholstery fabrics' },
  { value: '2', label: 'full room sets' },
]

export function Hero() {
  return (
    <section id="top" className="border-b border-border">
      <div className="mx-auto grid w-full max-w-6xl gap-12 px-6 py-16 lg:grid-cols-[1.05fr_1fr] lg:items-center lg:gap-16 lg:py-24">
        <div className="flex flex-col items-start gap-7">
          <p className="flex flex-wrap items-center gap-x-2 gap-y-1 font-mono text-xs tracking-tight text-muted-foreground">
            <span className="rounded-sm bg-secondary px-2 py-1 text-secondary-foreground">
              MAXScript
            </span>
            <span>3ds Max 2020+</span>
            <span aria-hidden="true">/</span>
            <span>Corona optional</span>
            <span aria-hidden="true">/</span>
            <span>MIT</span>
          </p>

          <h1 className="text-4xl font-medium tracking-tight text-balance sm:text-5xl lg:text-6xl">
            Render-ready furniture,
            <span className="text-primary"> generated in seconds</span>
          </h1>

          <p className="max-w-xl text-lg leading-relaxed text-muted-foreground text-pretty">
            FurnGen is a procedural furniture generator for Autodesk 3ds Max. Pick a category, a
            style and a fabric, then hit generate — you get grouped, named, fully materialled
            geometry that is ready to render, not a block-out to clean up.
          </p>

          <div className="flex flex-wrap items-center gap-3">
            <a
              href={`${REPO_URL}/releases/latest`}
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-2 rounded-md bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90"
            >
              Download the latest release
              <ArrowRight className="size-4" aria-hidden="true" />
            </a>
            <a
              href="#docs"
              className="inline-flex items-center gap-2 rounded-md border border-border px-5 py-2.5 text-sm font-medium transition-colors hover:bg-secondary"
            >
              <BookOpen className="size-4" aria-hidden="true" />
              Read the docs
            </a>
          </div>

          <dl className="mt-2 grid w-full grid-cols-2 gap-x-6 gap-y-5 border-t border-border pt-7 sm:grid-cols-4">
            {stats.map((stat) => (
              <div key={stat.label} className="flex flex-col gap-1">
                <dt className="sr-only">{stat.label}</dt>
                <dd className="font-mono text-2xl tracking-tight text-foreground">{stat.value}</dd>
                <p className="text-xs leading-relaxed text-muted-foreground">{stat.label}</p>
              </div>
            ))}
          </dl>
        </div>

        <div className="relative overflow-hidden rounded-lg border border-border bg-card">
          <Image
            src="/images/hero-sofa.png"
            alt="Studio render of a three-seat bouclé sofa with piping and tapered walnut legs, generated by FurnGen"
            width={1024}
            height={1024}
            priority
            className="h-auto w-full"
          />
          <p className="absolute bottom-3 left-3 rounded-sm bg-background/80 px-2 py-1 font-mono text-[11px] text-muted-foreground backdrop-blur-sm">
            straight · scandinavian · bouclé · seed 48213
          </p>
        </div>
      </div>
    </section>
  )
}
